### ISSUE TITLE
Глобальный поиск

### ISSUE THREAD

**Issue by hqamen** [heimdallr/books#210]
Вкладка поиска не работает. Можно найти книгу по автору, по серии, по жанру, по архиву. Но если знать только название книги, найти её не представляется возможным.
А так, всё работает идеально, лучший каталогизатор.

**Comment by heimdallr** [comment]
Там, наверное, не очень интуитивный UX. Чтобы выполнить поиск по названию, надо перейти на вкладку "Поиск", потом кликнуть ПКМ на левой навигационной панели, в контекстном меню выбрать Create new search.../Новый поиск... и в появившемся окне вбить искомую строку. Так пробовали?

**Comment by hqamen** [comment]
Так работает, да. Спасибо. Но интуитивность страдает, так как в остальных категориях это работает сразу. Даже в голову не пришло правой кнопкой тыкнуть. Но возможность просмотра сохранённого списка поисковых запросов тоже неплохая штука.
А ещё, можно-ли как-то запоминать выборы, например, указать русский язык книг и всегда его выбирать по умолчанию, а не кликать правой кнопкой. Или размер колонок зафиксировать, например?
Ну и до кучи, наберусь наглости и спрошу по поводу формата экспорта. Можно сделать несколько шаблонов, например?

**Comment by heimdallr** [comment]
>Так работает, да. Спасибо. Но интуитивность страдает, так как в остальных категориях это работает сразу. Даже в голову не пришло правой кнопкой тыкнуть. Но возможность просмотра сохранённого списка поисковых запросов тоже неплохая штука.

Неа, везде одинаково работает. Там общий код. Поиск (или фильтрация) делается среди того, что уже выбрано из базы и показывается на панели. При выборе раздела "Группы" тоже придётся пользоваться контекстным меню. Пожалуй, добавлю туда тулбарчик с кнопками new/delete, #211.

>А ещё, можно-ли как-то запоминать выборы, например, указать русский язык книг и всегда его выбирать по умолчанию, а не кликать правой кнопкой.

Долго думал, как такое можно сделать. Список языков - динамический, зависит от текущей выборки книг. Если зафиксировать один из языков, то при смене выборки список книг может оказаться пустым, хотя он просто отфильтрован по языку. Если считаете такое поведение полезным - подумаю ещё. Наверное можно будет завести настройку "Запоминать выбранный язык".

>Или размер колонок зафиксировать

Этого не понял. Ширину колонок можно менять, и она должны запоминаться, раздельно для каждого раздела и режима показа книг. Если у вас этого не происходит - заведите багрепорт, пожалуйста. С максимально подробным сценарием.

>по поводу формата экспорта. Можно сделать несколько шаблонов, например?

Да, конечно, сколько угодно. Можно настроить любой сценарий экспорта, через Главное меню/Настройки/Скрипты. Известные программе шаблоны можно узнать из контекстного меню строки "Аргументы".
<img width="1037" alt="image" src="https://github.com/heimdallr/books/assets/2487405/0beab46b-29ce-4379-b693-1f88b8ba28cd"> При настройке команд обратите внимание на 
* символ слэша, он должен быть виндовым `\`
* кавычки, иначе пробелы в именах файлов всё испортят.

Соответствующие пункты добавятся в меню экспорта
<img width="509" alt="image" src="https://github.com/heimdallr/books/assets/2487405/6c979a90-dab3-4e3d-bc93-f5aab4b3c57b">

>наберусь наглости и спрошу

Сколько угодно. Не стесняйтесь спрашивать и предлагать.

**Comment by hqamen** [comment]
Ширина колонок меняется. Но сбрасывается каждый раз при смене серии, например, или при смене автора. И сортировка не запоминается. Завтра попробую баг-репорт оформить.

**Comment by heimdallr** [comment]
Да, есть такой баг, всё руки не доходят до него. Ширина колонок запоминается только при смене раздела, а считывается при любой смене выборки книг. Про сортировку не замечал, спасибо. Жду багрепорта, этот тикет закрываю.
