### ISSUE TITLE
Сброс ширины колонок

### ISSUE THREAD

**Issue by hqamen** [heimdallr/books#212]
Ширина колонок сбрасывается при смене автора, серии, жанра, etc.

OS: Win 10 21H2 19044.4170
Версия программы: FLibrary 1.2.4

Шаги:
1. Открыть программу
2. Выбрать категорию Авторы
3. Изменить размер любого поля
4. Переключиться на другого автора

![FLibrary_3jJsMuAUXx](https://github.com/heimdallr/books/assets/172975920/d1bac4f9-d302-442d-950f-5b4036b2acb6)

**Comment by heimdallr** [comment]
Починено в версии 1.3.0. Прошу проверить. Если всё ок, прошу закрыть этот тикет. Ну или забить, тогда я сам его закрою через несколько дней :)
