### ISSUE TITLE
convertation to mobi

### ISSUE THREAD

**Issue by AlexeyWP** [heimdallr/books#75]
Hi! Is it possible to add a mobi-convertation feature when exporting to the device? Thank you!

**Comment by heimdallr** [comment]
It looks like moby is a proprietary format. I was unable to find a ready-made library for recording ebooks in this format. Or at least descriptions of it. Sorry :(

**Comment by heimdallr** [comment]
I will add the ability to create scripts that are used when exporting books. Then you can configure the launch of any converter yourself, and I will not violate any licenses, okay?

**Comment by AlexeyWP** [comment]
sounds good! will check this when possible

**Comment by heimdallr** [comment]
Task about scipts support: #77

**Comment by heimdallr** [comment]
An intermediate but working version released.
[mobi.reg.zip](https://github.com/heimdallr/books/files/13662769/mobi.reg.zip)
There is an example of a script in the form of a windows registry branch. You need to replace the path to your mobi-converter in the main menu "Settings->Script". Feature supports next macros for command parameters:
- %source_file%
- %user_destination_folder%
- %title%
- %file_ext%
- %file_name%
- %base_file_name%
- %uid%
- %author%
- %series%
- %seq_number%
- %file_size%

**Comment by heimdallr** [comment]
Feature fully released. Сommand parameters macros are accessible via the context menu. You can use conditional blocks like in MHL.

**Comment by AlexeyWP** [comment]
thank you! I'll try to figure it out
